import { useEffect, useState } from 'react'
import { AppShell } from '../components/AppShell'
import { PageChrome } from '../components/PageChrome'
import { LoadingSkeleton, ErrorState } from '../components/StatePanels'
import { StatusBadge } from '../components/StatusBadge'
import { Icon } from '../components/Icon'
import { getDataSources } from '../services/api'
import type { DataSource } from '../types/product'
const nav=[{id:'attention',label:'Attention',path:'/attention',icon:'alert' as const},{id:'personnel',label:'Personnel',path:'/personnel',icon:'person' as const},{id:'units',label:'Units',path:'/units',icon:'units' as const},{id:'trends',label:'Trends',path:'/trends',icon:'trend' as const},{id:'data',label:'Data & Signals',path:'/data/signals',icon:'data' as const},{id:'reviews',label:'Reviews',path:'/reviews',icon:'review' as const},{id:'governance',label:'Governance',path:'/governance',icon:'audit' as const}]
function push(p:string){history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))}
function statusTone(s:string){return s==='Healthy'?'ok':s==='Unavailable'?'danger':'warning'}
export default function DataCollection(){const [sources,setSources]=useState<DataSource[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notificationsOpen,setNotificationsOpen]=useState(false);useEffect(()=>{void getDataSources('AGGREGATE_OPERATIONS').then(r=>setSources(r.sources)).catch(e=>setError(e instanceof Error?e.message:'Data collection status is restricted in the current access context.')).finally(()=>setLoading(false))},[]);return <AppShell navItems={nav} activePath="/data/collection" query="" searchResults={[]} searchOpen={false} onQueryChange={()=>{}} onSearchSelect={()=>{}} onNavigate={push} notificationsOpen={notificationsOpen} onToggleNotifications={()=>setNotificationsOpen(v=>!v)}>{loading?<LoadingSkeleton/>:<PageChrome eyebrow="DATA / COLLECTION" title="Data Collection Management" subtitle="Monitor the availability and quality of the demonstration data streams"><section><div className="panel-title section-gap">Active data streams</div><div className="stream-grid">{error?<ErrorState message={error}/>:sources.map((s)=><div className="stream-card" key={s.name}><div className="stream-card-top"><div className="source-icon"><Icon name="data" size={18}/></div><StatusBadge label={s.status} tone={statusTone(s.status)}/></div><h2>{s.name}</h2><p>{s.classification}</p><div className="stream-rule"/><div className="stream-meta"><span>Records</span><strong>{s.records.toLocaleString()}</strong></div><div className="stream-meta"><span>Last updated</span><strong>{s.last_updated?new Date(s.last_updated).toLocaleString():'Not available'}</strong></div></div>)}</div></section><section className="collection-grid"><div className="panel"><div className="panel-heading"><div><div className="panel-title">Manual data entry</div><h2>Future operational collection</h2></div></div><div className="collection-actions"><div><strong>Voluntary wellness information</strong><p>Optional input. Not displayed in operational summaries. Production integration concept only.</p><span className="muted">Not connected in demonstration environment.</span></div><div><strong>Incident information</strong><p>Current incident records are synthetic and already present in the demonstration pipeline.</p><span className="muted">No live entry system is connected.</span></div></div></div><div className="panel"><div className="panel-title">Privacy controls</div><div className="privacy-card"><Icon name="shield" size={22}/><div><strong>Pseudonymization at source</strong><p>Prototype security controls protect identifiers before analytics-facing use.</p></div><span className="toggle-on">ON</span></div><div className="panel-note">Production data connectors and identity federation are not connected in this demonstration environment.</div></div></section></PageChrome>}</AppShell>}
