import { useEffect, useState } from 'react'
import { AppShell } from '../components/AppShell'
import { PageChrome } from '../components/PageChrome'
import { ErrorState, LoadingSkeleton } from '../components/StatePanels'
import { Icon } from '../components/Icon'
import { getDataSources } from '../services/api'
import type { DataSource } from '../types/product'
const nav=[{id:'attention',label:'Attention',path:'/attention',icon:'alert' as const},{id:'personnel',label:'Personnel',path:'/personnel',icon:'person' as const},{id:'units',label:'Units',path:'/units',icon:'units' as const},{id:'trends',label:'Trends',path:'/trends',icon:'trend' as const},{id:'data',label:'Data & Signals',path:'/data/signals',icon:'data' as const},{id:'reviews',label:'Reviews',path:'/reviews',icon:'review' as const},{id:'governance',label:'Governance',path:'/governance',icon:'audit' as const}]
function push(p:string){history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))}
export default function DataSignals(){const [sources,setSources]=useState<DataSource[]>([]),[env,setEnv]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notificationsOpen,setNotificationsOpen]=useState(false);useEffect(()=>{void getDataSources('AGGREGATE_OPERATIONS').then(r=>{setSources(r.sources);setEnv(r.environment)}).catch(e=>setError(e instanceof Error?e.message:'Data source information is restricted in the current access context.')).finally(()=>setLoading(false))},[])
return <AppShell navItems={nav} activePath="/data/signals" query="" searchResults={[]} searchOpen={false} onQueryChange={()=>{}} onSearchSelect={()=>{}} onNavigate={push} notificationsOpen={notificationsOpen} onToggleNotifications={()=>setNotificationsOpen(v=>!v)}>{loading?<LoadingSkeleton/>:<PageChrome eyebrow="DATA & SIGNALS" title="Data & Signals Architecture" subtitle="Where operational information becomes welfare decision support" right={<span className="demo-pill">{env||'Demonstration environment'}</span>}>
<div className="pipeline"><div><span>01</span><strong>Data sources</strong><small>Operational records</small></div><i/><div><span>02</span><strong>Ingestion & validation</strong><small>Validated source files</small></div><i/><div><span>03</span><strong>Operational indicators</strong><small>Longitudinal features</small></div><i/><div><span>04</span><strong>Usual pattern</strong><small>Personal/context</small></div><i/><div><span>05</span><strong>Predictive signal</strong><small>Calibrated output</small></div><i/><div><span>06</span><strong>Welfare support</strong><small>Human review</small></div></div>
{error?<ErrorState message={error}/>:<><section className="panel"><div className="panel-heading"><div><div className="panel-title">Source status</div><h2>Current demonstration streams</h2></div><span className="muted">{sources.length} sources</span></div><div className="source-grid">{sources.map(s=><div key={s.name} className="source-card"><div className="source-icon"><Icon name="data" size={18}/></div><div><strong>{s.name}</strong><small>{s.classification}</small></div><span className="source-status"><b/> {s.status}</span><div className="source-meta"><span>{s.records.toLocaleString()} records</span><span>{s.last_updated?new Date(s.last_updated).toLocaleString():''}</span></div></div>)}</div></section><section className="panel"><div className="panel-title">Data handling</div><div className="policy-grid"><div><Icon name="shield" size={19}/><strong>Operational-first</strong><p>Core decision support works from operational data; voluntary wellness information is supplementary.</p></div><div><Icon name="lock" size={19}/><strong>Privacy boundary</strong><p>Raw source contents and wellness responses are not shipped to the browser by this surface.</p></div><div><Icon name="check" size={19}/><strong>Synthetic demonstration</strong><p>Current environment uses synthetic longitudinal data and is not connected to live government systems.</p></div></div></section></>}
<div className="privacy-note">Data provenance is presented for transparency; production ingestion and identity infrastructure remain outside the demonstration environment.</div>
</PageChrome>}</AppShell>}
