import { useEffect, useState } from 'react'
import { AppShell } from '../components/AppShell'
import { PageChrome } from '../components/PageChrome'
import { LoadingSkeleton, ErrorState } from '../components/StatePanels'
import { StatusBadge } from '../components/StatusBadge'
import { Icon } from '../components/Icon'
import { getAuditView, getSystemHealth } from '../services/api'
import type { AuditRecord } from '../types/product'
const nav=[{id:'attention',label:'Attention',path:'/attention',icon:'alert' as const},{id:'personnel',label:'Personnel',path:'/personnel',icon:'person' as const},{id:'units',label:'Units',path:'/units',icon:'units' as const},{id:'trends',label:'Trends',path:'/trends',icon:'trend' as const},{id:'data',label:'Data & Signals',path:'/data/signals',icon:'data' as const},{id:'reviews',label:'Reviews',path:'/reviews',icon:'review' as const},{id:'governance',label:'Governance',path:'/governance',icon:'audit' as const}]
function push(p:string){history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))}
export default function Governance(){
 const [audit,setAudit]=useState<{chain_valid:boolean;event_count:number;events:AuditRecord[]}|null>(null),[health,setHealth]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notificationsOpen,setNotificationsOpen]=useState(false)
 useEffect(()=>{void Promise.all([getAuditView(),getSystemHealth()]).then(([a,h])=>{setAudit(a);setHealth(h)}).catch(e=>setError(e instanceof Error?e.message:'Access restricted: governance information requires the authorized audit or administration workspace.')).finally(()=>setLoading(false))},[])
 return <AppShell navItems={nav} activePath="/governance" query="" searchResults={[]} searchOpen={false} onQueryChange={()=>{}} onSearchSelect={()=>{}} onNavigate={push} notificationsOpen={notificationsOpen} onToggleNotifications={()=>setNotificationsOpen(v=>!v)}>
  {loading?<LoadingSkeleton/>:error?<div className="restricted-panel"><Icon name="lock" size={24}/><h2>Access restricted</h2><p>The current Welfare Officer workspace does not have governance/audit authorization. Switch to an authorized security or administration workspace to view this information.</p></div>:<PageChrome eyebrow="GOVERNANCE" title="Governance & Security Audit" subtitle="System oversight, access controls, and audit integrity">
   <div className="governance-grid"><div className="panel"><div className="panel-title">System integrity</div><div className="integrity-box"><div><strong>Audit chain</strong><StatusBadge label={audit?.chain_valid?'Verified':'Failed'} tone={audit?.chain_valid?'ok':'danger'}/></div><small>{audit?.event_count??0} events in current view</small></div><div className="health-lines"><span>Access controls <b>Active</b></span><span>Security boundary <b>{health?.governance?.security_boundary??'Prototype'}</b></span><span>Audit chain <b>{audit?.chain_valid?'Healthy':'Failed'}</b></span></div></div><div className="panel"><div className="panel-title">Role-based access</div><div className="role-list"><div><Icon name="person" size={18}/><span><strong>Welfare Officers</strong><small>Individual welfare review</small></span><b>Restricted</b></div><div><Icon name="units" size={18}/><span><strong>Command Leadership</strong><small>Aggregate operations</small></span><b>Aggregate</b></div><div><Icon name="audit" size={18}/><span><strong>Auditors / Administrators</strong><small>Governance and system health</small></span><b>Governance</b></div></div></div></div>
   <section className="panel audit-panel"><div className="panel-heading"><div><div className="panel-title">Immutable audit log</div><h2>Recent governance events</h2></div><span className="muted">Showing {audit?.events.length??0}</span></div><div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>UTC</th><th>ROLE</th><th>ACTION</th><th>PURPOSE</th><th>STATUS</th></tr></thead><tbody>{audit?.events.map((e,i)=><tr key={`${e.timestamp}-${i}`}><td>{new Date(e.timestamp).toLocaleString()}</td><td><StatusBadge label={e.actor_role}/></td><td>{e.event_type.replaceAll('_',' ')}</td><td>{e.purpose.replaceAll('_',' ')}</td><td><StatusBadge label={e.outcome} tone={e.outcome==='ALLOWED'?'ok':'danger'}/></td></tr>)}</tbody></table></div></section>
  </PageChrome>}
 </AppShell>
}
