import { useEffect, useMemo, useState } from 'react'
import { PageChrome } from '../components/PageChrome'
import { AppShell } from '../components/AppShell'
import { ErrorState, LoadingSkeleton } from '../components/StatePanels'
import { StatusBadge } from '../components/StatusBadge'
import { TrendIndicator, type Trend } from '../components/TrendIndicator'
import { Icon } from '../components/Icon'
import { getPersonDetail, transitionWorkflow, recordWorkflowFeedback, scheduleWorkflowFollowUp, completeWorkflowFollowUp } from '../services/api'
import type { PersonDetail } from '../types/dashboard'
import type { WorkflowItem, WorkflowState } from '../types/workflow'
import { FORTIFY_PURPOSE, FORTIFY_ROLE } from '../services/api'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const nav=[
 {id:'attention',label:'Attention',path:'/attention',icon:'alert' as const},{id:'personnel',label:'Personnel',path:'/personnel',icon:'person' as const},
 {id:'units',label:'Units',path:'/units',icon:'units' as const},{id:'trends',label:'Trends',path:'/trends',icon:'trend' as const},
 {id:'data',label:'Data & Signals',path:'/data/signals',icon:'data' as const},{id:'reviews',label:'Reviews',path:'/reviews',icon:'review' as const},{id:'governance',label:'Governance',path:'/governance',icon:'audit' as const}
]
function push(p:string){history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))}
function bandLabel(b:string){return b==='HIGH'?'Needs attention':b==='MODERATE'?'Worth checking':'No current concern'}
function statusLabel(s:WorkflowState){return ({NEW:'New',ACKNOWLEDGED:'Acknowledged',IN_REVIEW:'Being reviewed',SUPPORT_PLANNED:'Support planned',SUPPORT_COMPLETED:'Support completed',COMPLETED:'Support completed',FOLLOW_UP_SCHEDULED:'Follow-up scheduled',FOLLOW_UP_DUE:'Follow-up due',FOLLOW_UP_COMPLETED:'Follow-up completed',CLOSED:'Closed',DEFERRED:'Deferred',DISMISSED:'Dismissed'})[s] ?? s.replaceAll('_',' ')}
function trend(history:PersonDetail['history']):Trend{if(history.length<2)return 'STABLE';const a=history[history.length-1]?.risk_probability??0,b=history[history.length-2]?.risk_probability??0;return a-b>0.015?'RISING':a-b<-0.015?'IMPROVING':'STABLE'}
function formatDateTime(value:string|null|undefined){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString([], {day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:true})}
function nextTransitions(state:WorkflowState):Array<[WorkflowState,string,string]>{return ({
 NEW:[['ACKNOWLEDGED','Acknowledge','ACKNOWLEDGE_REVIEW'],['DISMISSED','Dismiss','DISMISS_REVIEW']],
 ACKNOWLEDGED:[['IN_REVIEW','Start review','START_REVIEW'],['DEFERRED','Defer','DEFER_REVIEW'],['DISMISSED','Dismiss','DISMISS_REVIEW']],
 IN_REVIEW:[['SUPPORT_PLANNED','Plan support','PLAN_SUPPORT'],['DEFERRED','Defer','DEFER_REVIEW'],['DISMISSED','Dismiss','DISMISS_REVIEW']],
 SUPPORT_PLANNED:[['SUPPORT_COMPLETED','Mark support completed','SUPPORT_COMPLETED_BY_HUMAN'],['COMPLETED','Mark support completed','SUPPORT_COMPLETED_BY_HUMAN'],['DEFERRED','Defer','DEFER_REVIEW']],
 SUPPORT_COMPLETED:[['FOLLOW_UP_SCHEDULED','Schedule follow-up','FOLLOW_UP_SCHEDULED'],['CLOSED','Close case','CASE_CLOSED'],['SUPPORT_PLANNED','Plan further support','FURTHER_SUPPORT_REQUIRED']],
 COMPLETED:[['FOLLOW_UP_SCHEDULED','Schedule follow-up','FOLLOW_UP_SCHEDULED'],['CLOSED','Close case','CASE_CLOSED'],['SUPPORT_PLANNED','Plan further support','FURTHER_SUPPORT_REQUIRED']],
 FOLLOW_UP_SCHEDULED:[], FOLLOW_UP_DUE:[], FOLLOW_UP_COMPLETED:[['CLOSED','Close case','CASE_CLOSED'],['SUPPORT_PLANNED','Plan further support','FURTHER_SUPPORT_REQUIRED']],
 DEFERRED:[['ACKNOWLEDGED','Reopen review','REOPEN_REVIEW'],['IN_REVIEW','Resume review','RESUME_REVIEW'],['DISMISSED','Dismiss','DISMISS_REVIEW']], CLOSED:[], DISMISSED:[]
}[state] ?? [])}
function supportState(state:WorkflowState|undefined){return state==='SUPPORT_COMPLETED'||state==='COMPLETED'||state==='FOLLOW_UP_SCHEDULED'||state==='FOLLOW_UP_DUE'||state==='FOLLOW_UP_COMPLETED'||state==='CLOSED'}
export default function PersonProfile({personId}:{personId:string}){
 const [detail,setDetail]=useState<PersonDetail|null>(null),[workflow,setWorkflow]=useState<WorkflowItem|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[helpfulness,setHelpfulness]=useState(3),[comment,setComment]=useState(''),[followUpRequested,setFollowUpRequested]=useState(false),[scheduleValue,setScheduleValue]=useState('')
 const load=async()=>{setLoading(true);setError(null);try{const d=await getPersonDetail(personId);setDetail(d);if(d.workflow?.workflow_item_id)setWorkflow(d.workflow as WorkflowItem);else setWorkflow(null)}catch(e){setError(e instanceof Error?e.message:'Personnel record could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[personId])
 const trendValue=useMemo(()=>detail?trend(detail.history):'STABLE',[detail])
 if(loading)return <AppShell navItems={nav} activePath="/person" query="" searchResults={[]} searchOpen={false} onQueryChange={()=>{}} onSearchSelect={()=>{}} onNavigate={push} notificationsOpen={notificationsOpen} onToggleNotifications={()=>setNotificationsOpen(v=>!v)}><LoadingSkeleton/></AppShell>
 if(error||!detail)return <AppShell navItems={nav} activePath="/person" query="" searchResults={[]} searchOpen={false} onQueryChange={()=>{}} onSearchSelect={()=>{}} onNavigate={push} notificationsOpen={notificationsOpen} onToggleNotifications={()=>setNotificationsOpen(v=>!v)}><ErrorState message={error??'Personnel record not found.'} onRetry={()=>void load()}/></AppShell>
 const latest=detail.latest
 const state=workflow?.workflow_state??'NEW'
 const displayState:WorkflowState=workflow?.followup?.status==='DUE'?'FOLLOW_UP_DUE':state
 const actions=nextTransitions(state)
 const doTransition=async(next:WorkflowState,reason:string)=>{if(!workflow)return;setBusy(true);try{const updated=await transitionWorkflow(workflow.workflow_item_id,next,reason);setWorkflow(updated);setDetail(await getPersonDetail(personId));}catch(e){setError(e instanceof Error?e.message:'Workflow action could not be recorded.')}finally{setBusy(false)}}
 const saveFeedback=async()=>{if(!workflow)return;setBusy(true);try{const updated=await recordWorkflowFeedback(workflow.workflow_item_id,helpfulness,comment,followUpRequested);setWorkflow(updated)}catch(e){setError(e instanceof Error?e.message:'Feedback could not be recorded.')}finally{setBusy(false)}}
 const schedule=async()=>{if(!workflow||!scheduleValue)return;setBusy(true);try{const updated=await scheduleWorkflowFollowUp(workflow.workflow_item_id,new Date(scheduleValue).toISOString());setWorkflow(updated);setDetail(await getPersonDetail(personId));setScheduleValue('')}catch(e){setError(e instanceof Error?e.message:'Follow-up could not be scheduled.')}finally{setBusy(false)}}
 const completeFollowup=async()=>{if(!workflow?.followup)return;setBusy(true);try{const updated=await completeWorkflowFollowUp(workflow.followup.followup_id);setWorkflow(updated);setDetail(await getPersonDetail(personId))}catch(e){setError(e instanceof Error?e.message:'Follow-up could not be completed.')}finally{setBusy(false)}}
 const activeSupport=supportState(state)
 return <AppShell navItems={nav} activePath="/person" query="" searchResults={[]} searchOpen={false} onQueryChange={()=>{}} onSearchSelect={()=>{}} onNavigate={push} notificationsOpen={notificationsOpen} onToggleNotifications={()=>setNotificationsOpen(v=>!v)}>
  <PageChrome eyebrow="PERSONNEL / PROFILE" title={detail.person_id} subtitle={`Unit ${detail.unit_id??'—'} · ${detail.role??'Operational context'}`} right={<button className="back-button" type="button" onClick={()=>push('/attention')}>← Attention</button>}>
   <div className="profile-status-strip"><StatusBadge label={bandLabel(latest.risk_band)} tone={latest.risk_band==='HIGH'?'high':latest.risk_band==='MODERATE'?'moderate':'low'}/><TrendIndicator trend={trendValue}/><span className="status-text">Current concern · {bandLabel(latest.risk_band)}</span><span className="status-text">Support status · {statusLabel(displayState)}</span>{workflow?.requires_human_review&&!['CLOSED','DISMISSED'].includes(state)?<span className="review-required"><Icon name="lock" size={13}/> Human review required</span>:null}</div>
   <section className="profile-grid two">
    <div className="panel"><div className="panel-title">What changed</div><div className="change-list"><div><b>Workload</b><span>{trendValue==='RISING'?'↑ Increased':'→ No major change'}</span></div><div><b>Night-duty exposure</b><span>{trendValue==='RISING'?'↑ Increased':'→ No major change'}</span></div><div><b>Recovery</b><span>{latest.feasibility_status.includes('CONSTRAINED')?'↓ Constrained opportunity':'→ Available'}</span></div></div></div>
    <div className="panel"><div className="panel-title">Usual pattern</div><p className="panel-copy">This view compares the current operational pattern with the person's own recent history. It does not interpret missing voluntary reporting as a concern.</p><div className="mini-metrics"><span><b>{Math.round(latest.risk_probability*100)}%</b><small>technical detail</small></span><span><b>{detail.date_range[1]}</b><small>latest available day</small></span></div></div>
   </section>
   <section className="panel"><div className="panel-title">Recent trend</div><div className="trend-chart"><ResponsiveContainer width="100%" height={220}><LineChart data={detail.history}><XAxis dataKey="date" hide/><YAxis domain={[0,1]} tickFormatter={(v)=>`${Math.round(Number(v)*100)}%`} width={42}/><Tooltip formatter={(value)=>[`${Math.round(Number(value)*100)}%`,'Signal']} labelFormatter={(v)=>String(v)}/><Line type="monotone" dataKey="risk_probability" dot={false} stroke="var(--navy)" strokeWidth={2}/></LineChart></ResponsiveContainer></div></section>
   <section className="profile-grid two">
    <div className="panel"><div className="panel-title">Why FORTIFY brought this up</div><p className="panel-copy">{latest.contributing_operational_signals || 'No additional contributing operational signals were recorded for this date.'}</p><details className="technical"><summary>How FORTIFY reached this</summary><p>Technical model information is secondary context. The welfare journey is based on operational signals and the person's usual pattern.</p></details></div>
    <div className="panel support-panel"><div className="panel-title">Suggested next step</div><h2>{latest.recommended_action.replaceAll('_',' ')}</h2><p>{latest.adjustment_recommendation || 'Review the suggested support with the current operational context.'}</p><div className="feasibility-block"><span>Can support be scheduled now?</span><strong>{latest.feasibility_status==='FEASIBLE'?'Can be scheduled':latest.feasibility_status==='FEASIBLE_WITH_ADJUSTMENT'?'Can be scheduled with adjustment':latest.feasibility_status==='CONSTRAINED'?'Needs scheduling':'Not currently scheduled'}</strong><small>{latest.constraint_flags || 'No additional constraint recorded.'}</small></div></div>
   </section>
   {activeSupport?<section className="panel lifecycle-panel"><div className="panel-heading"><div><div className="panel-title">Support status</div><h2>{statusLabel(displayState)}</h2></div><span className="audit-inline"><Icon name="lock" size={14}/> Access logged</span></div>
      {workflow?.support_event&&<div className="support-event"><strong>Support provided</strong><span>{formatDateTime(workflow.support_event.completed_at)}</span><small>Recorded by {workflow.support_event.actor_role==='WELFARE_OFFICER'?'Welfare Officer':workflow.support_event.actor_role}</small></div>}
      {workflow?.feedback?<div className="feedback-readonly"><div className="panel-title">Personnel feedback</div><p>{'★'.repeat(workflow.feedback.helpfulness)}{'☆'.repeat(5-workflow.feedback.helpfulness)} · {['','Not helpful','Slightly helpful','Helpful','Very helpful','Extremely helpful'][workflow.feedback.helpfulness]}</p><small>Submitted {formatDateTime(workflow.feedback.submitted_at)}</small>{workflow.feedback.comment&&<small>{workflow.feedback.comment}</small>}{workflow.feedback.follow_up_requested&&<small>Follow-up requested</small>}</div>:state==='SUPPORT_COMPLETED'||state==='COMPLETED'?<div className="feedback-form"><div className="panel-title">Personnel feedback <small>Voluntary</small></div><label>How helpful was the support you received?<select value={helpfulness} onChange={e=>setHelpfulness(Number(e.target.value))}><option value={1}>1 — Not helpful</option><option value={2}>2 — Slightly helpful</option><option value={3}>3 — Helpful</option><option value={4}>4 — Very helpful</option><option value={5}>5 — Extremely helpful</option></select></label><label><span>Optional comment</span><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} placeholder="No comment required" /></label><label className="check-row"><input type="checkbox" checked={followUpRequested} onChange={e=>setFollowUpRequested(e.target.checked)}/> Follow-up requested</label><button className="button primary" type="button" disabled={busy} onClick={()=>void saveFeedback()}>{busy?'Saving…':'Record voluntary feedback'}</button></div>:null}
      {(state==='SUPPORT_COMPLETED'||state==='COMPLETED')&&<div className="followup-plan"><div className="panel-title">Next step</div><p>Schedule a follow-up after support to keep the case connected to human care.</p><div className="followup-schedule-form"><input type="datetime-local" value={scheduleValue} onChange={e=>setScheduleValue(e.target.value)} aria-label="Follow-up date and time"/><button className="button primary" type="button" disabled={busy||!scheduleValue} onClick={()=>void schedule()}>Schedule follow-up</button></div></div>}
      {workflow?.followup&&<div className="followup-current"><div><div className="panel-title">Follow-up</div><strong>{workflow.followup.status==='COMPLETED'?'Follow-up completed':workflow.followup.status==='DUE'?'Follow-up due':'Follow-up scheduled'}</strong><span>{formatDateTime(workflow.followup.scheduled_for)}</span></div>{workflow.followup.status!=='COMPLETED'&&<button className="button primary" type="button" disabled={busy} onClick={()=>void completeFollowup()}>Complete follow-up</button>}</div>}
   </section>:null}
   <section className="panel workflow-panel"><div className="panel-heading"><div><div className="panel-title">Human review</div><h2>{statusLabel(state)}</h2></div><span className="audit-inline"><Icon name="lock" size={14}/> Access logged</span></div><div className="workflow-actions">{busy?<span className="muted">Saving workflow action…</span>:actions.map(([next,label,reason])=><button key={`${next}-${label}`} className={`button ${next==='DISMISSED'?'secondary':'primary'}`} type="button" onClick={()=>void doTransition(next,reason)}>{label}</button>)}{actions.length===0?<span className="muted">No human transition is available from this state.</span>:null}</div>{workflow?.history?.length?<div className="audit-history">{workflow.history.map(event=><div key={event.event_id}><span>{formatDateTime(event.timestamp)}</span><strong>{statusLabel(event.new_state)}</strong><small>{event.actor_role==='WELFARE_OFFICER'?'Welfare Officer':event.actor_role} · {event.reason_code}</small></div>)}</div>:<div className="empty-history">No human actions have been recorded yet.</div>}</section>
   <div className="privacy-note">{FORTIFY_ROLE} · {FORTIFY_PURPOSE} · Operational welfare information only · No raw wellness responses are shown.</div>
  </PageChrome>
 </AppShell>
}
