import { useEffect, useState } from 'react'
import { AppShell } from '../components/AppShell'
import { PageChrome } from '../components/PageChrome'
import { LoadingSkeleton, ErrorState } from '../components/StatePanels'
import { getDashboardTrend } from '../services/api'
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip } from 'recharts'
const nav=[{id:'attention',label:'Attention',path:'/attention',icon:'alert' as const},{id:'personnel',label:'Personnel',path:'/personnel',icon:'person' as const},{id:'units',label:'Units',path:'/units',icon:'units' as const},{id:'trends',label:'Trends',path:'/trends',icon:'trend' as const},{id:'data',label:'Data & Signals',path:'/data/signals',icon:'data' as const},{id:'reviews',label:'Reviews',path:'/reviews',icon:'review' as const},{id:'governance',label:'Governance',path:'/governance',icon:'audit' as const}]
function push(p:string){history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))}
export default function Trends(){const[p,setP]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notificationsOpen,setNotificationsOpen]=useState(false);useEffect(()=>{void getDashboardTrend(30).then(setP).catch(e=>setError(e instanceof Error?e.message:'Trend data could not be loaded.')).finally(()=>setLoading(false))},[]);return <AppShell navItems={nav} activePath="/trends" query="" searchResults={[]} searchOpen={false} onQueryChange={()=>{}} onSearchSelect={()=>{}} onNavigate={push} notificationsOpen={notificationsOpen} onToggleNotifications={()=>setNotificationsOpen(v=>!v)}>{loading?<LoadingSkeleton/>:<PageChrome eyebrow="TRENDS" title="Operational Trends" subtitle="Decision-focused changes over the latest available period">{error?<ErrorState message={error}/>:<><section className="panel"><div className="panel-title">Is operational pressure increasing?</div><div className="trend-chart"><ResponsiveContainer width="100%" height={320}><LineChart data={p.points}><XAxis dataKey="date" tickFormatter={(v)=>String(v).slice(5)} minTickGap={28}/><YAxis domain={[0,1]} tickFormatter={(v)=>`${Math.round(Number(v)*100)}%`} width={42}/><Tooltip/><Line type="monotone" dataKey="average_probability" stroke="var(--navy)" strokeWidth={2} dot={false} name="Average signal"/></LineChart></ResponsiveContainer></div></section><section className="panel"><div className="trend-callouts"><div><strong>What changed?</strong><p>Recent operational welfare signals vary over time rather than remaining static.</p></div><div><strong>Why does it matter?</strong><p>Workload and scheduling constraints can change the support context alongside the signal.</p></div><div><strong>What can I do?</strong><p>Review affected personnel or units from the Attention and Units views.</p></div></div></section></>}</PageChrome>}</AppShell>}
